apiVersion: v1
kind: Secret
metadata:
  name: analytics-engine-secret
  namespace: analytics
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://username:password@cluster.mongodb.net/?retryWrites=true&w=majority"
  DATABASE_NAME: "analytics_db"
  COLLECTION_NAME: "data"